#!/bin/sh
echo "************************"
echo -n "Please Wait ..."
sleep 1

mv /Library/TweakInject.bak /Library/TweakInject
echo " done !"

declare -a cydia
cydia=($CYDIA)

if [[ $1 == remove ]]; then
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    else
    	echo "Please respring your device."
    fi
fi

echo "************************"
echo "************************"
sleep 1
echo -n "-By ::"
sleep 1
echo " Karwan BK (Karwanbk@yahoo.com)"
echo "************************"


 
